
import java.util.HashSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *1 inicio botones deshabilitados (set.Enabled)
 * 2 boton para habilitar botones
 * 3 boton para deshabilitar
 * 4 agregar boton con X
 * 5 botn reset
 * 
 * @author jose.zapatagom
 */
import javax.swing.JOptionPane;
public class Tateti extends javax.swing.JFrame {

    /**
     * Creates new form Tateti
     
    int x1;
    int x2;
    int x3;
    int x4;
    int x5;
    int x6;
    int x7;
    int x8;
    int x9;
    
        
    public void ganador(){
        if (x1.getText()=="X" && x2.getText()=="X" && x3.getText()=="X"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x4.getText()=="X" && x5.getText()=="X" && x6.getText()=="X"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x7.getText()=="X" && x8.getText()=="X" && x9.getText()=="X"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x1.getText()=="X" && x4.getText()=="X" && x7.getText()=="X"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x2.getText()=="X" && x5.getText()=="X" && x8.getText()=="X"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x3.getText()=="X" && x6.getText()=="X" && x9.getText()=="X"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x1.getText()=="X" && x5.getText()=="X" && x9.getText()=="X"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x3.getText()=="X" && x5.getText()=="X" && x7.getText()=="X"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        
        if (x1.getText()=="O" && x2.getText()=="O" && x3.getText()=="O"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x4.getText()=="O" && x5.getText()=="O" && x6.getText()=="O"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x7.getText()=="O" & x8.getText()=="O" & x9.getText()=="O"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x1.getText()=="O" && x4.getText()=="O" && x7.getText()=="O"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x2.getText()=="O" && x5.getText()=="O" && x8.getText()=="O"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x3.getText()=="O" && x6.getText()=="O" && x9.getText()=="O"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x1.getText()=="O" && x5.getText()=="O" && x9.getText()=="O"){
            JOptionPane.showMessageDialog(null, "Ganó!!!");        
        }
        if (x3.getText()=="O" && x5.getText()=="O" && x7.getText()=="O"){
            JOptionPane.showMessageDialog(null, "Ganó!!!"); 
    }*/
    public Tateti(){
        initComponents();
        x1.setEnabled(false);
        x2.setEnabled(false);
        x3.setEnabled(false);
        x4.setEnabled(false);
        x5.setEnabled(false);
        x6.setEnabled(false);
        x7.setEnabled(false);
        x8.setEnabled(false);
        x9.setEnabled(false);
        op1juan.setEnabled(false);
        op2pedro.setEnabled(false);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        op1juan = new javax.swing.JRadioButton();
        op2pedro = new javax.swing.JRadioButton();
        x2 = new javax.swing.JButton();
        x3 = new javax.swing.JButton();
        x4 = new javax.swing.JButton();
        x1 = new javax.swing.JButton();
        x5 = new javax.swing.JButton();
        x9 = new javax.swing.JButton();
        x6 = new javax.swing.JButton();
        x7 = new javax.swing.JButton();
        x8 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jugador2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inicio.setText("A JUGAR!!!");
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        stop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        stop.setText("STOP");
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        op1juan.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        op1juan.setText("Juan");
        op1juan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op1juanMouseClicked(evt);
            }
        });
        getContentPane().add(op1juan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        op2pedro.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        op2pedro.setText("Pedro");
        op2pedro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                op2pedroMouseClicked(evt);
            }
        });
        getContentPane().add(op2pedro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        x2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x2MouseClicked(evt);
            }
        });
        getContentPane().add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 88, 57, 48));

        x3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x3MouseClicked(evt);
            }
        });
        getContentPane().add(x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 88, 57, 48));

        x4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x4MouseClicked(evt);
            }
        });
        getContentPane().add(x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 164, 57, 48));

        x1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x1MouseClicked(evt);
            }
        });
        x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1ActionPerformed(evt);
            }
        });
        getContentPane().add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 88, 57, 48));

        x5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x5MouseClicked(evt);
            }
        });
        getContentPane().add(x5, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 164, 57, 48));

        x9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x9MouseClicked(evt);
            }
        });
        getContentPane().add(x9, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 242, 57, 48));

        x6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x6MouseClicked(evt);
            }
        });
        x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x6ActionPerformed(evt);
            }
        });
        getContentPane().add(x6, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 164, 57, 48));

        x7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x7MouseClicked(evt);
            }
        });
        getContentPane().add(x7, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 242, 57, 48));

        x8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        x8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x8MouseClicked(evt);
            }
        });
        getContentPane().add(x8, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 242, 57, 48));

        reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset.setText("RESET");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jugador2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jugador2.setText("JUGADOR");
        jugador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugador2MouseClicked(evt);
            }
        });
        jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TA TE TI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, 50));

        jButton1.setText("Inicio");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tateti2.2.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 470, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x6ActionPerformed

    private void x2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x2MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x2.setText("X");
           if(x2.getText()=="X"){
           x2.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           
           }
       }
       else{
           x2.setText("0");
           x2.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       }  
        
       
    }//GEN-LAST:event_x2MouseClicked

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        // TODO add your handling code here:
        x1.setEnabled(true);
        x2.setEnabled(true);
        x3.setEnabled(true);
        x4.setEnabled(true);
        x5.setEnabled(true);
        x6.setEnabled(true);
        x7.setEnabled(true);
        x8.setEnabled(true);
        x9.setEnabled(true);
        op1juan.setEnabled(true);
        op2pedro.setEnabled(true);
        op2pedro.setSelected(false);
        op1juan.setSelected(true);
    }//GEN-LAST:event_inicioMouseClicked

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
        // TODO add your handling code here:
        x1.setEnabled(false);
        x2.setEnabled(false);
        x3.setEnabled(false);
        x4.setEnabled(false);
        x5.setEnabled(false);
        x6.setEnabled(false);
        x7.setEnabled(false);
        x8.setEnabled(false);
        x9.setEnabled(false);
        op1juan.setEnabled(false);
        op2pedro.setEnabled(false);
    }//GEN-LAST:event_stopMouseClicked

    private void x1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x1MouseClicked
        // TODO add your handling code here:
               
        if (op1juan.isSelected()==true){
            x1.setText("X");
            if(x1.getText()=="X"){
            x1.setEnabled(false);
            op1juan.setSelected(false);
            op2pedro.setSelected(true);
            }
        }
        else{
            x1.setText("0");
            x1.setEnabled(false);  
            op1juan.setSelected(true);
            op2pedro.setSelected(false);
        }    
    }//GEN-LAST:event_x1MouseClicked

    private void x3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x3MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
            x3.setText("X");
            if(x3.getText()=="X"){
            x3.setEnabled(false);
            op1juan.setSelected(false);
            op2pedro.setSelected(true);
            }
        }
        else{
            x3.setText("0");
            x3.setEnabled(false);  
            op1juan.setSelected(true);
            op2pedro.setSelected(false);
        } 
       
    }//GEN-LAST:event_x3MouseClicked

    private void x4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x4MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x4.setText("X");
           if(x4.getText()=="X"){
           x4.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x4.setText("0");
           x4.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
       
    }//GEN-LAST:event_x4MouseClicked

    private void x5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x5MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x5.setText("X");
           if(x5.getText()=="X"){
           x5.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x5.setText("0");
           x5.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
        
    }//GEN-LAST:event_x5MouseClicked

    private void x6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x6MouseClicked
        // TODO add your handling code here:
      if (op1juan.isSelected()==true){
           x6.setText("X");
           if(x6.getText()=="X"){
           x6.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x6.setText("0");
           x6.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
       
    }//GEN-LAST:event_x6MouseClicked

    private void x7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x7MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x7.setText("X");
           if(x7.getText()=="X"){
           x7.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x7.setText("0");
           x7.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
        
    }//GEN-LAST:event_x7MouseClicked

    private void x8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x8MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x8.setText("X");
           if(x8.getText()=="X"){
           x8.setEnabled(false);
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           }
       }
       else{
           x8.setText("0");
           x8.setEnabled(false);  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
       } 
    }//GEN-LAST:event_x8MouseClicked

    private void x9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x9MouseClicked
        // TODO add your handling code here:
        if (op1juan.isSelected()==true){
           x9.setText("X");
           if(x9.getText()=="X"){
           op1juan.setSelected(false);
           op2pedro.setSelected(true);
           x9.setEnabled(false);
           }
       }
       else{
           x9.setText("0");  
           op1juan.setSelected(true);
           op2pedro.setSelected(false);
           x9.setEnabled(false);
       } 
    }//GEN-LAST:event_x9MouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        // TODO add your handling code here:
        
        x1.setText("");
        x2.setText("");
        x3.setText("");
        x4.setText("");
        x5.setText("");
        x6.setText("");
        x7.setText("");
        x8.setText("");
        x9.setText("");
    }//GEN-LAST:event_resetMouseClicked

    private void jugador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugador2MouseClicked
        // TODO add your handling code here:
          
    op1juan.setSelected(false);
    op2pedro.setSelected(true);
    }//GEN-LAST:event_jugador2MouseClicked

    private void op1juanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op1juanMouseClicked
        // TODO add your handling code here:
        op1juan.setSelected(true);
        op2pedro.setSelected(false);
        
    }//GEN-LAST:event_op1juanMouseClicked

    private void op2pedroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_op2pedroMouseClicked
        // TODO add your handling code here:
        op1juan.setSelected(false);
        op2pedro.setSelected(true);
    }//GEN-LAST:event_op2pedroMouseClicked

    private void x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_x1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Ventana1 v1 =new Ventana1();
        v1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador2ActionPerformed
        // TODO add your handling code here:
               
    }//GEN-LAST:event_jugador2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tateti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tateti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tateti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tateti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tateti().setVisible(true);
            }
        });
        
        
 
     
     
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jugador2;
    private javax.swing.JRadioButton op1juan;
    private javax.swing.JRadioButton op2pedro;
    private javax.swing.JButton reset;
    private javax.swing.JButton stop;
    private javax.swing.JButton x1;
    private javax.swing.JButton x2;
    private javax.swing.JButton x3;
    private javax.swing.JButton x4;
    private javax.swing.JButton x5;
    private javax.swing.JButton x6;
    private javax.swing.JButton x7;
    private javax.swing.JButton x8;
    private javax.swing.JButton x9;
    // End of variables declaration//GEN-END:variables
}
