/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Gabriela Andrade     13/07/2017
 * @author Español
 */

import javax.swing.JOptionPane;
public class Ventana3 extends javax.swing.JFrame {

    /**                                       
     * Creates new form Ventana3
     */
    int ap=0;
     int monto=0;
    
   
    
    public Ventana3() {
        initComponents();
        simple.setVisible(false);
        doble.setVisible(false);
        triple.setVisible(false);
        txt2.setVisible(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio3 = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        simple = new javax.swing.JButton();
        doble = new javax.swing.JButton();
        triple = new javax.swing.JButton();
        apuesta = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio3.setText("Inicio");
        inicio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicio3MouseClicked(evt);
            }
        });
        getContentPane().add(inicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        label3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label3.setText("APUESTA");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, -1));

        simple.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        simple.setText("Simple");
        simple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpleMouseClicked(evt);
            }
        });
        getContentPane().add(simple, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        doble.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        doble.setText("Doble");
        doble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dobleMouseClicked(evt);
            }
        });
        doble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobleActionPerformed(evt);
            }
        });
        getContentPane().add(doble, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        triple.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        triple.setText("Triple");
        triple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tripleMouseClicked(evt);
            }
        });
        getContentPane().add(triple, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        apuesta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        apuesta.setText("Iniciar apuesta");
        apuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apuestaMouseClicked(evt);
            }
        });
        getContentPane().add(apuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 120, 30));

        label1.setBackground(new java.awt.Color(102, 102, 102));
        label1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        label1.setText("Ingrese monto de apuesta");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 30));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, 30));

        txt2.setColumns(20);
        txt2.setRows(5);
        jScrollPane1.setViewportView(txt2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 270, 60));

        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio3MouseClicked
        // TODO add your handling code here:
        Ventana1 v1 =new Ventana1();
        v1.setVisible(true);
        dispose();
    }//GEN-LAST:event_inicio3MouseClicked

    private void apuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apuestaMouseClicked
        // TODO add your handling code here:
        simple.setVisible(true);
        doble.setVisible(true);
        triple.setVisible(true);
        txt2.setVisible(true);
        
        
        
    }//GEN-LAST:event_apuestaMouseClicked

    private void simpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpleMouseClicked
        // TODO add your handling code here:
        monto= Integer.parseInt(this.txt1.getText());
        ap= monto*1;
        txt2.setText("Usted realizo una apuesta simple de $"+monto+"\n"+"Total apuesta de $"+String.valueOf(ap));    
    }//GEN-LAST:event_simpleMouseClicked

    private void dobleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobleMouseClicked
        // TODO add your handling code here:label1.setVisible(false);
        monto= Integer.parseInt(this.txt1.getText());
        ap= monto*2;
        txt2.setText("Usted realizo una apuesta doble de $"+monto+"\n"+"Total apuesta de $"+String.valueOf(ap));
    }//GEN-LAST:event_dobleMouseClicked

    private void tripleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tripleMouseClicked
        // TODO add your handling code here:
        monto= Integer.parseInt(this.txt1.getText());
        ap= monto*3;
        txt2.setText("Usted realizo una apuesta triple de $"+monto+"\n"+"Total apuesta de $"+String.valueOf(ap));
    }//GEN-LAST:event_tripleMouseClicked

    private void dobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobleActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt1.setText("");
        txt2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apuesta;
    private javax.swing.JButton doble;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton inicio3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JButton simple;
    private javax.swing.JButton triple;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextArea txt2;
    // End of variables declaration//GEN-END:variables
}
