/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Gabriela Andrade     13/07/2017
 * @author Español
 */

import javax.swing.JOptionPane;
public class Ventana3 extends javax.swing.JFrame {

    /**                                       
     * Creates new form Ventana3
     */
   
    
    public Ventana3() {
        initComponents();
        simple.setVisible(false);
        doble.setVisible(false);
        triple.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio3 = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        simple = new javax.swing.JButton();
        doble = new javax.swing.JButton();
        triple = new javax.swing.JButton();
        monto1 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        btntateti = new javax.swing.JButton();
        btnbanco = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio3.setText("Inicio");
        inicio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicio3MouseClicked(evt);
            }
        });
        getContentPane().add(inicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        label3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label3.setText("APLICACION");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 240, -1));

        simple.setText("Simple");
        simple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpleMouseClicked(evt);
            }
        });
        getContentPane().add(simple, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        doble.setText("Doble");
        doble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dobleMouseClicked(evt);
            }
        });
        getContentPane().add(doble, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        triple.setText("Triple");
        triple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tripleMouseClicked(evt);
            }
        });
        getContentPane().add(triple, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        monto1.setText("Apuesta");
        monto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monto1MouseClicked(evt);
            }
        });
        getContentPane().add(monto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 80, -1));

        label1.setBackground(new java.awt.Color(102, 102, 102));
        label1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        label1.setText("Ingrese monto de apuesta");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 30));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, 30));

        btntateti.setText("TATETI");
        btntateti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntatetiMouseClicked(evt);
            }
        });
        btntateti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntatetiActionPerformed(evt);
            }
        });
        getContentPane().add(btntateti, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        btnbanco.setText("BANCO");
        btnbanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbancoMouseClicked(evt);
            }
        });
        getContentPane().add(btnbanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 320, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio3MouseClicked
        // TODO add your handling code here:
        Ventana1 v1 =new Ventana1();
        v1.setVisible(true);
        dispose();
    }//GEN-LAST:event_inicio3MouseClicked

    private void monto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monto1MouseClicked
        // TODO add your handling code here:
        simple.setVisible(true);
        doble.setVisible(true);
        triple.setVisible(true);
        
    }//GEN-LAST:event_monto1MouseClicked

    private void simpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpleMouseClicked
        // TODO add your handling code here:
        label1.setVisible(false);
        txt1.setVisible(false);
        monto1.setVisible(false);
        simple.setVisible(false);
        doble.setVisible(false);
        triple.setVisible(false);
        JOptionPane.showMessageDialog(null,"Usted realizo una apuesta SIMPLE");
    }//GEN-LAST:event_simpleMouseClicked

    private void dobleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobleMouseClicked
        // TODO add your handling code here:label1.setVisible(false);
        txt1.setVisible(false);
        monto1.setVisible(false);
        simple.setVisible(false);
        doble.setVisible(false);
        triple.setVisible(false);
        JOptionPane.showMessageDialog(null,"Usted realizo una apuesta DOBLE");
    }//GEN-LAST:event_dobleMouseClicked

    private void tripleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tripleMouseClicked
        // TODO add your handling code here:
        label1.setVisible(false);
        txt1.setVisible(false);
        monto1.setVisible(false);
        simple.setVisible(false);
        doble.setVisible(false);
        triple.setVisible(false);
        JOptionPane.showMessageDialog(null,"Usted realizo una apuesta TRIPLE");
    }//GEN-LAST:event_tripleMouseClicked

    private void btntatetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntatetiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btntatetiActionPerformed

    private void btntatetiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntatetiMouseClicked
        // TODO add your handling code here:
        Tateti t1 =new Tateti();
        t1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btntatetiMouseClicked

    private void btnbancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbancoMouseClicked
        // TODO add your handling code here:
        CajeroAutomatico c1= new CajeroAutomatico();
        c1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbancoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbanco;
    private javax.swing.JButton btntateti;
    private javax.swing.JButton doble;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton inicio3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JButton monto1;
    private javax.swing.JButton simple;
    private javax.swing.JButton triple;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
