/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Español
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
      setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        presentacion = new javax.swing.JButton();
        apli = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        inicio1 = new javax.swing.JButton();
        btnbanco = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        titulo2 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        titulo5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        presentacion.setText("Presentación");
        presentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                presentacionMouseClicked(evt);
            }
        });
        presentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentacionActionPerformed(evt);
            }
        });
        getContentPane().add(presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        apli.setText("Apuesta");
        apli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apliMouseClicked(evt);
            }
        });
        getContentPane().add(apli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        inicio1.setText("Inicio");
        getContentPane().add(inicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        btnbanco.setText("Banco");
        btnbanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbancoMouseClicked(evt);
            }
        });
        getContentPane().add(btnbanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jButton2.setText("TaTeTi");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        titulo2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setText("PRESENTACION");
        getContentPane().add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, -1));

        titulo3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        titulo3.setForeground(new java.awt.Color(255, 255, 255));
        titulo3.setText("INICIO");
        getContentPane().add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 20, 130, -1));

        titulo5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        titulo5.setForeground(new java.awt.Color(255, 255, 255));
        titulo5.setText("APLICACIONES");
        getContentPane().add(titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv4.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void presentacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presentacionMouseClicked
        // TODO add your handling code here:
        Ventana2 v2 = new Ventana2 ();//para hacer que la venta 2 aparezca
        v2.setVisible(true);//llama a ventana 2
        dispose(); //oculta venta 1
    }//GEN-LAST:event_presentacionMouseClicked

    private void apliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apliMouseClicked
        // TODO add your handling code here:
        Ventana3 v3 = new Ventana3 ();//para hacer que la venta 2 aparezca
        v3.setVisible(true);//llama a ventana 2
        dispose(); //oculta venta 1
    }//GEN-LAST:event_apliMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void presentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentacionActionPerformed

    private void btnbancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbancoMouseClicked
        // TODO add your handling code here:
        CajeroAutomatico c1= new CajeroAutomatico();
        c1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbancoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Tateti t1 =new Tateti();
        t1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apli;
    private javax.swing.JButton btnbanco;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton inicio1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton presentacion;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo5;
    // End of variables declaration//GEN-END:variables
}
